### PR TITLE
Fix/css html fixes

### PR DESCRIPTION
**Pull request by ecupaio**
I made some big changes here to the layout and how the files are organized but the footer is acting weird, not ready for approval yet so I would avoid pushing until I know more why there's CSS that gets applied to the footer on the interior pages vs the homepages in your version.

### CODE REVIEW

**Comment by Speaslee** [comment]
This was actually super helpful, thank you!

**Comment by ecupaio** [comment]
no problemo, I might have messed some things up seeing as how it's on a template, but you get the gist: 
- you can inherit a parent layout and use the {{ content }} variable to add your custom code so you're not copy pasting the entire dom over and over again
- you can use includes to drop in reusable code like i did with the HTML head and you can actually add arguments to those includes if you want to customize them: https://jekyllrb.com/docs/includes/

Real talk I don;t think this is a good template. He uses fixed positioning for the footer which is really weird. I would HIGHLY suggest using a [template from cloudcannon](https://cloudcannon.com/templates/) as you'll have a CMS set up and ready to roll. Personal plan is free and I really like them.

**Comment by ecupaio** [comment]
you can use [my template](https://github.com/ecupaio/jekyll-template), but I need to do some work on my NPM depenendencies and maybe just git rid of grunt entirely. going to stackoverflow and mashing in terminal commands until it works is not a recipe for success and im figuring that out on my new laptop lol. I can say however, (slaps hood), this baby is optimized for speed and SEO so you can have a performant site from the get go.

**Comment by Speaslee** [comment]
Yeah I'll look into switching to cloud cannon.  I am going to go ahead and close this pr but thank you so much for your help, I really really appreciate it!

**Pull request closed without merging**
